# Worker name (unique per account)
name = "cors-stream-proxy"

# Your Cloudflare account ID
account_id = "0dec72346e94bae11c1c9fb5a7a16b71"

# Entry point
main = "src/index.js"

# Compatibility settings
compatibility_date = "2024-10-01"
compatibility_flags = ["nodejs_compat"]

# Deploy to workers.dev
workers_dev = true

# Build configuration (optional)
[build]
command = ""
upload = { format = "modules" }

# Production environment
[env.production]
name = "cors-stream-proxy-prod"

# Development environment
[env.development]
name = "cors-stream-proxy-dev"
vars = { DEBUG = "true", LOG_LEVEL = "debug" }
