# Name of your Worker (must be unique across your account)
name = "cors-stream-proxy"

# Cloudflare Account ID (keep yours as-is)
account_id = "0dec72346e94bae11c1c9fb5a7a16b71"

# Main entry file
main = "src/index.js"

# Compatibility for modern Cloudflare Workers
compatibility_date = "2024-10-01"
compatibility_flags = ["nodejs_compat"]

# Deploy to workers.dev
workers_dev = true

# Resource limit (required!)
[limits]
cpu_ms = 50

# Optional: if you need to build (you can remove if not using a bundler)
[build]
command = ""
upload = { format = "modules" }

# Production environment
[env.production]
name = "cors-stream-proxy-prod"

# Development environment
[env.development]
name = "cors-stream-proxy-dev"
vars = { DEBUG = "true", LOG_LEVEL = "debug" }
