# Worker name (unique per account)
name = "cors-stream-proxy"

# Your Cloudflare account ID
account_id = "0dec72346e94bae11c1c9fb5a7a16b71"

# Entry point file for your Worker
main = "src/index.js"

# Enable modern runtime features
compatibility_date = "2024-10-01"
compatibility_flags = ["nodejs_compat"]

# Deploy to workers.dev subdomain
workers_dev = true

# Resource limits
[limits]
cpu_ms = 50

# Optional: build config (remove if not used)
[build]
command = "npm run build"
upload = { format = "modules" }

# Production environment
[env.production]
name = "cors-stream-proxy-prod"

# Development environment
[env.development]
name = "cors-stream-proxy-dev"
vars = { DEBUG = "true", LOG_LEVEL = "debug" }
